language: java
jdk:
    - oraclejdk8
script:
    - cd translatr && bin/activator clean coverage test && bin/activator coverageAggregate
after_success:
    - cd translatr && bin/activator coveralls
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
