dist: trusty
os: linux

jobs:
  include:
    - language: java
      addons:
        postgresql: "9.4"
      jdk: oraclejdk8
      services:
        - docker

      before_script:
        - psql -V
        - psql -c 'create user translatr;' -U postgres
        - psql -c 'create database "translatr-test";' -U postgres
        - psql -c 'grant all privileges on database "translatr-test" TO translatr;' -U postgres
      script:
        - bin/activator jacoco:cover -Dconfig.file=test.conf
        - bin/activator it:test -Dconfig.file=it.conf
#      after_success:
#        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#        - bin/activator docker:publish
      cache:
        timeout: 86400
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
      before_cache:
        # Cleanup the cached directories to avoid unnecessary cache updates
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
        - find $HOME/.sbt        -name "*.lock"               -print -delete

    - language: node_js
      node_js: "12.0"
      before_install:
        - cd ui
      script:
        - npm run build:ci
        - npm run coveralls
