version: "2"
services:
    db-translatr:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
            - ./docker/entrypoint-initdb.d:/docker-entrypoint-initdb.d
    redis-translatr:
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
