version: "2"
volumes:
  pg-data:
services:
  db-translatr:
    image: postgres
    command: postgres -c 'max_connections=200'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./docker/entrypoint-initdb.d:/docker-entrypoint-initdb.d
  keycloak-translatr:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_USER: translatr
      KEYCLOAK_PASSWORD: translatr
      DB_VENDOR: h2
