apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: client
          image: resamsel/translatr-loadgenerator:3.1.0-5
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: loadgenerator-config
