version: "2"
volumes:
    translatr-data:
services:
    service-translatr:
        image: resamsel/play-translatr:1.0-SNAPSHOT
        ports:
            - "9000:9000"
        environment:
            JAVA_OPTS: -Dplay.crypto.secret=my-docker-secret -Ddb.default.url=jdbc:h2:/opt/docker/data/db -Dplay.evolutions.db.default.autoApply=true
        volumes:
            - translatr-data:/opt/docker/data
    service-db-translatr:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - translatr-data:/var/lib/postgresql/data
            - ./docker/entrypoint-initdb.d:/docker-entrypoint-initdb.d
