version: "2"
volumes:
    translatr-data:
services:
    service-translatr:
        image: resamsel/play-translatr:1.0-SNAPSHOT
        ports:
            - "9000:9000"
        environment:
            JAVA_OPTS: -Dplay.crypto.secret=my-docker-secret -Ddb.default.driver=org.h2.Driver -Ddb.default.url=jdbc:h2:/opt/docker/data/db -Dplay.evolutions.db.default.autoApply=true
        volumes:
            - translatr-data:/opt/docker/data
