version: "2"
volumes:
    translatr-h2:
    translatr-data:
services:
#    translatr:
#        image: resamsel/play-translatr:1.0-SNAPSHOT
#        ports:
#            - "9000:9000"
#        environment:
#            APPLICATION_SECRET: _L3ghjA;7xnzzuwD0ZxKX:ABTere[x5I?31<^nQ[=7v/AqG^wk4h;Q76NUKm3KEG
#            JAVA_OPTS: -Dconfig.resource=docker.conf
#        volumes:
#            - translatr-h2:/opt/docker/data
    db-translatr:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - translatr-data:/var/lib/postgresql/data
            - ./docker/entrypoint-initdb.d:/docker-entrypoint-initdb.d
