name: Docker

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  # Build and push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Run server build and deploy docker image
        run: bin/activator stage docker:publish

      - name: Run load generator build and deploy docker image
        working-directory: ui
        run: |
          npm run build:lets-generate:docker
          npm run publish:lets-generate:docker
