name: Play Framework CI

on:
  push:
    branches:
    - main
    - feature/*
    - release/*
  pull_request:
    branches:
    - main
    - feature/*
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build
      run: bin/activator compile stage

    - name: Test
      run: bin/activator test -Dconfig.file=test.conf

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: target/test-reports/*.xml

    - name: Generate Report
      id: xunit-viewer
      uses: AutoModality/action-xunit-viewer@v1
      with:
        results: target/test-reports
        output: test-report-sbt.html
    - name: Attach Report
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.xunit-viewer.outputs.report-name }}
        path: ${{ steps.xunit-viewer.outputs.report-file }}
